name: Deploy GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Проверка наличия папки и перемещение файлов
      - name: Copy files from 'christmas-shop'
        run: |
          if [ -d "christmas-shop" ]; then
            cp -r christmas-shop/* .
            rm -rf christmas-shop
          else
            echo "Directory 'christmas-shop' does not exist!"
            exit 1
          fi

      # Шаг 3: Настройка Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Шаг 4: Коммит и пуш изменений
      - name: Commit and Push
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push
